stages:
   - build
   - deploy

variables:
  BUCKET_NAME: devsight.app # Your bucket name

# build stage
build_app:
   image: node:10
   stage: build
   only:
      - master
   script:
      - npm install
      - npm run build
   cache:
     paths:
       - node_modules/
   artifacts:
      paths:
         # build folder
         - dist/
      expire_in: 1 hour

# production stage
production:
   image: python:latest
   stage: deploy
   only:
      - master
   script:
      - pip install awscli
      - aws s3 sync ./dist s3://${BUCKET_NAME} --delete